name: BetterSurvival
version: '1.0-SNAPSHOT'
main: fr.cyri.BetterSurvival
api-version: '1.21'
author: cyri:)

commands:
  sethome:
    description: Défini un home
    usage: /sethome <name>
  home:
    description: Téléporte un joueur à un home défini
    usage: /home <name>
  homes:
    description: Liste tous les homes d'un joueur
    usage: /homes
  removehome:
    description: Supprime un home existant
    usage: /removehome <name>